version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: progressus_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progressus_database
    volumes:
      - ./dump.sql:/tmp/dump.sql